config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#landing'

  get 'home', to: 'dashboard#home', as: :home
  match 'signup', to: 'dashboard#signup', as: :signup, via: [:get, :post]

  devise_for :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :check_user_authentication, only: [:landing]

  def home;end

  def landing;end

  def signup
    @user = User.where(email: params[:email]).first_or_initialize
  end

  private

  def check_user_authentication
    if user_signed_in?
      redirect_to home_path
    end    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/common/_header.html.erb
<div class="row header">
  <div class="col-md-2"></div>
  <div class="col-md-8 middle"></div>
  <div class="col-md-2">
    <% if user_signed_in? %>
      <%= link_to 'Signout', destroy_user_session_path, method: :delete, class: 'logout' %>
    <% else %>
      <% if params[:action].eql?('landing') %>
        <%= link_to 'Sign in', new_user_session_path, class: 'login' %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/dashboard/home.html.erb
<h1>Welcome</h1>
<h2>If you are reading this message, means you have loggedin successfully!</h2>
<h3>Assume it as your random page!</h3>

app/views/dashboard/landing.html.erb
<div class="row signup-page">
  <div class="col-md-6 left-side">
    <%= image_tag "/assets/slack-img.png" %>
  </div>
  <div class="col-md-6 right-side">
    <h1>Where work happens</h1>
    <p>When your team needs to kick off a project, hire a new employee, deploy some code, review a sales contract, finalize next year's budget, measure an A/B test, plan your next office opening, and more, Slack has you covered.</p>
    <%= form_tag(signup_path, method: :post) do |f| %>
      <div class="field">
        <%= label_tag :email %><br>
        <%= text_field_tag :email, '', placeholder: 'Your Email....', class: 'form-control' %>
      </div>
      <div class="action">
        <%= submit_tag 'Get Started', class: 'ready-btn' %>
      </div>
      <p>Already using Slack? <%= link_to 'Sign in', new_user_session_path %>.</p>
    <% end %>
  </div>
</div>

app/views/dashboard/signup.html.erb
<div class="col-md-8 offset-2 landing-page">
  <div class="col-md-12 box">
    <h1>Just a few quick things to set up your account...</h1>
    <% resource_name = :user %>
    <% url = @user.persisted? ? session_path(resource_name) : registration_path(resource_name) %>
    <% method_type = 'post' %>
    <% action_text = @user.persisted? ? 'Login! ->' : 'Ready! ->'  %>

    <%= form_for(@user, as: resource_name, url: url, html: { method: method_type.to_sym }) do |f| %>
      <%= f.hidden_field :email %>

      <% if @user.persisted? %>
        <p>Email already exist in our DB!</p>
      <% else %>
        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name, placeholder: 'Name', class: 'form-control' %>
        </div>
      <% end %>

      <div class="field">
        <%= f.label :password %><br>
        <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
      </div>
      <% unless @user.persisted? %>
        <div id="password_strength"></div>
      <% end %>

      <div class="action">
        <%= submit_tag action_text, class: 'ready-btn form-control' %>
      </div>
    <% end %>
  </div>
</div>


<script>
  $("#user_password").bind("keyup", function() {
    var color, i, passed, regex, strength;
    if ($(this).val().length === 0) {
      $("#password_strength").html("");
      return;
    }
    else if ($(this).val().length < 6) {
      $("#password_strength").html("Min. length 6");
      return; 
    }
    else if ($(this).val() == 'password') {
      $("#password_strength").html("Invalid!");
      $(this).val('');
      return;  
    }
    else if ($(this).val() == '12345678') {
      $("#password_strength").html("Invalid");
      $(this).val('');
      return;  
    }
    regex = new Array();
    regex.push("[A-Z]");
    regex.push("[a-z]");
    regex.push("[0-9]");
    regex.push("[$@$!%*#?&]");
    passed = 0;
    i = 0;
    while (i < 3) {
      if (new RegExp(regex[i]).test($(this).val())) {
        passed++;
      }
      i++;
    }
    if (passed > 2 && $(this).val().length > 5) {
      passed++;
    }
    if (passed > 3 && new RegExp(regex[3]).test($(this).val())) {
      passed++;
    }
    if (passed > 4 && $(this).val().length > 5) {
      passed++;
    }

    color = "";
    strength = "";

    switch (passed) {
      case 0:
      case 1:
        strength = "Weak";
        color = "red";
        break;
      case 2:
        strength = "Weak";
        color = "red";
        break;
      case 3:
        strength = "Weak";
        color = "red";
        break;
      case 4:
        strength = "Good";
        color = "darkorange";
        break;
      case 5:
        strength = "Strong";
        color = "green";
        break;
      case 6:
        strength = "Very Strong";
        color = "darkgreen";
    }
    $("#password_strength").html(strength);
    return $("#password_strength").css("color", color);
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoTest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: 'common/header' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>